First homework review
Georgi-Ginduzov/.NETSchoolCoherentSolutions pull request #1
Opened 2024-04-23 21:01 UTC by Georgi-Ginduzov

First homework is ready for review.

2024-04-24 11:09 UTC, IgorKheidorov requested changes
Please remove binary files from git repo, and then re-create PR. Git repo has to contain *.cs. *csproj and *.sln files only.

2024-04-25 19:49 UTC, Georgi-Ginduzov commented
Removed them. Should I merge?

2024-04-26 11:53 UTC, IgorKheidorov requested changes
Please fix comments and issues

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/WriteDuodecimalNumbersInRange/Program.cs
> +
a can be greater then b, or negative. Fix case

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/WriteDuodecimalNumbersInRange/Program.cs
> +                }
LINQ is not available for first tasks, please calculate manually

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/WriteDuodecimalNumbersInRange/Program.cs
> +                {
You convert 10 to 12-base system and back.. For what? It is not needed for the task. If you even do this please move this functionality to separate methods

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/WriteDuodecimalNumbersInRange/Program.cs
> +                {
it will be quit enough calculate number of remainders ==10

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ISBNControlDigitCalculation/Program.cs
> +
Seems it does't work according to the task, please be more accurate

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ISBNControlDigitCalculation/Program.cs
> +
Wrong control digit

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ArrayInputOutput/Program.cs
> +            Console.WriteLine("\n\nThe array with unique values is: ");
Resize uniqueNumbersArray to actual size

2024-04-26 11:53 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ArrayInputOutput/Program.cs
> +            Console.WriteLine("The original array is: ");
Output array in a separate method, do not repeat yourself

2024-04-29 20:34 UTC, Georgi-Ginduzov commented
Resolved all comments

2024-04-30 09:39 UTC, IgorKheidorov requested changes

2024-04-30 09:39 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ISBNControlDigitCalculation/Program.cs
> +            controlDigit = 11 - remainder;
controlDigit = (11 - remainder)%11->  to process case when reminder = 0

2024-04-30 09:39 UTC, IgorKheidorov commented on SyntaxBasicsHomework/WriteDuodecimalNumbersInRange/Program.cs
> +        }
This is not the solution of the task, you have to convert input to duodecimal system, and calculate the number of А in its duodecimal representation

2024-04-30 09:39 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ArrayInputOutput/Program.cs
> +    {
Code style with methods names

2024-04-30 18:49 UTC, Georgi-Ginduzov commented
Hey I am curious about my code style. I would be grateful if you give me an opinion about my code readability.

2024-05-07 12:15 UTC, IgorKheidorov requested changes

2024-05-07 12:15 UTC, IgorKheidorov commented on SyntaxBasicsHomework/ISBNControlDigitCalculation/Program.cs
> +            controlDigit = 11 - remainder;
controlDigit = (11 - remainder)%11; if reminder = 0 you will have controlDigit = 11, that wrong

2024-05-10 16:11 UTC, merged